### PR TITLE
Mark 3.12.0 release

### PR DESCRIPTION
**Pull request by mzyromski-atlassian**

### CODE REVIEW

**Comment by mzyromski-atlassian** [comment]
Artifacts: https://packages.atlassian.com/maven-central/com/atlassian/performance/tools/virtual-users/3.12.0/

**Review by wyrzyk — APPROVED** [review]

**Comment by dagguh** [comment]
WRT red CI, I'll try local repro

**Review by dagguh — APPROVED** [review]

**Comment by dagguh** [comment]
Works locally. I suspect staele CI cache.

**Comment by dagguh** [comment]
I mega-nuked all local Gradle caches, still green locally: `rm -rf ~/.gradle/caches && git clean -fdx && ./gradlew compileTestKotlin`.

**Comment by dagguh** [comment]
BTW https://circleci.com/docs/2.0/caching/#cache-size :

> We recommend keeping cache sizes under 500MB. This is our upper limit for corruption checks because above this limit check times would be excessively long.

https://app.circleci.com/pipelines/github/atlassian/virtual-users/66/workflows/7946c498-a93f-4beb-ac74-3bacac9ef597/jobs/73 :
> Found a cache from build 68 at v3-dependencies-sv4sjSamHv0M1CRPZjaKa2zK4bAWdvrvw4XFGdJaYmE=
Size: 740 MiB

Our cache keys only look at `build.gradle.kts`, but dependency-locks can change without changing that file.
Raised https://ecosystem.atlassian.net/browse/JPERF-709

**Comment by dagguh** [comment]
@mzyromski-atlassian what happens after a rerun?

**Comment by dagguh** [comment]
Ok, got the repro: you gotta `git tag -d release-3.12.0`.
If `./gradlew currentVersion` is `3.12.0-SNAPSHOT`, then this fails like that.

**Comment by dagguh** [comment]
PS. the long-term solution to break this pseudo-cycle would be to get a lib, which can setup Jira, without depending on VUs. E.g. extracting `vu-infra` out of `infrastructure`.

**Comment by dagguh** [comment]
@mzyromski-atlassian I remember now. You gotta push the new tags to your fork. So `git fetch upstream --tags && git push origin --tags`. The papercut is small, but hurts

**Comment by mzyromski-atlassian** [comment]
@dagguh, thanks for looking into this. I did the workaround and reran the CI. 🤞

**Pull request merged**
