### PR TITLE
JPERF-707: Download the connector via `curl` rather than `wget`

### PR DESCRIPTION
**Pull request by dagguh**

### CODE REVIEW

**Comment by dagguh** [comment]
Running it 4 times to see if curl is less flaky than wget: https://app.circleci.com/pipelines/github/dagguh/virtual-users?branch=fix-flaky-mysql-connector

**Comment by dagguh** [comment]
They're all green! 🎉

**Comment by mzyromski-atlassian** [comment]
Why would wget be more flaky then curl?

**Review by mzyromski-atlassian — APPROVED** [review]

**Comment by dagguh** [comment]
cURL is a very mature lib/tool. It might have some internal retry/TCP/HTTP robustness.
No idea TBH, but 6/6 curl runs were green while 3/4 wget runs were red.

**Pull request merged**
