### PR TITLE
Increase `apt-get update` timeout in `SudoSshUbuntuImage`

### PR DESCRIPTION
**Pull request by wyrzyk**
It failed on master 3 times in a row.

### CODE REVIEW

**Comment by wyrzyk** [comment]
> Resolved 'com.atlassian.performance.tools:virtual-users:3.6.2' which is not part of the dependency lock state

@dagguh  How can we fix that? I don't have all the tags, because I don't use my master branch and it's never up to date. I always target `atlassian/virtual-users` repo.

**Comment by dagguh** [comment]
> > Resolved 'com.atlassian.performance.tools:virtual-users:3.6.2' which is not part of the dependency lock state
> 
> @dagguh How can we fix that? I don't have all the tags, because I don't use my master branch and it's never up to date. I always target `atlassian/virtual-users` repo.

Push all upstream tags to your fork

**Comment by dagguh** [comment]
You'll have to do it every time the transitive self-dependency bumps. E.g. if we bump `infrastructure` and the new version requires a higher minimum VU version, and your `currentVersion` is lower than that, then you gotta refresh the tags.
Refreshing upstream tags should be done anyway, if you ever care about `currentVersion`, e.g. if you work on SNAPSHOTs.

**Comment by dagguh** [comment]
> It failed on master 3 times in a row.

Proof:
* https://circleci.com/gh/atlassian/virtual-users/9
* https://circleci.com/gh/atlassian/virtual-users/10

**Pull request merged**
