### PR TITLE
JPERF-640: Add existing `RestUserGenerator` behavioral contracts

### PR DESCRIPTION
**Pull request by dagguh**
This is mostly a dummy PR to test the Jira-GH integration

### CODE REVIEW

**Comment by dagguh** [comment]
[JPERF-640] testing links according to https://github.com/integrations/jira/blob/master/README.md#link-issues-in-github

**Comment by dagguh** [comment]
Another linking test: [JPERF-640]

**Comment by dagguh** [comment]
It worked! ⤴️

**Comment by dagguh** [comment]
FYI @mzyromski-atlassian ⤴️

**Comment by mzyromski-atlassian** [comment]
Is this PR just for test or is it supposed to be eventually merged?

**Comment by dagguh** [comment]
Let's close this.
Initially I wanted to merge this, but then I added a "dummy commit" 4eb04953552c2bd326e8a66f27fbd2807cd7bc8e, so it's no longer clean. And the diff is meh. `RestUserGenerator` already promises "Generating users via REST" behavior via its name.

**Pull request closed without merging**
