### PR TITLE
retry user creation

### PR DESCRIPTION
**Pull request by pbruski**

### CODE REVIEW

**Comment by dagguh** [comment]
Here's a related PR in HWR: https://github.com/atlassian/jira-hardware-exploration/pull/73
We found that Jira doesn't like too many concurrent user creation requests. So we decided to add `SerialUserGenerator` (a lock) to serialize user creation per VU node. We also added `JitterBackoff` to avoid harmonics across VU nodes.

**Comment by dagguh** [comment]
If we find the root cause and it will be unfixable in Jira, we'll have to compromise, e.g.:
* spread the user creation over a much longer period of time - degrading the perf feedback loop
* prepopulate users in datasets - adding maintenance cost to existing datasets and adding complexity to dataset selection and usage

**Comment by wyrzyk** [comment]
@dagguh, @pbruski  In Jira stress test, we used to create users during the load. It helped to avoid contention on user creation and timeouts.

**Comment by dagguh** [comment]
Did it actually help?

```
    private class PatientLogInAction(private val logInAction: Action) : Action {
        private val logger: Logger = LogManager.getLogger(this::class.java)
        override fun run() {
            while (true) {
                try {
                    return logInAction.run()
                } catch (e: Exception) {
                    logger.debug("Failed to log in, ${e.message}")
                }
            }
        }
    }
```
We saw this loop for the entire duration. 470 000 failed attempts. A portion of VUs were only spinning in this loop, never applying browser load.

These failures are silent and hard to notice due to infinite retries.

**Comment by pbruski** [comment]
What I've seen today was a case where the node was returning 502 to all requests, despite the /status endpoint reporting it as healthly. So backoff/retries won't help. I'll see if another case like that happens.

**Comment by dagguh** [comment]
Thanks for the investigation @pbruski!

**Pull request closed without merging**
