### PR TITLE
Upgrade log4j from 2.10.0 to 2.17.1

### PR DESCRIPTION
**Pull request by rjatkins**

### CODE REVIEW

**Comment by pczuj** [comment]
@rjatkins, thanks for contribution. In this repository [we have some dependency locks on log4j version](https://github.com/atlassian/virtual-users/search?q=log4j%3Alog4j). 

I believe we should also relock those - my guess is that the CI on this branch is failing due to incompatibility between locks and the explicit dependency: https://app.circleci.com/pipelines/github/atlassian/virtual-users/85/workflows/a57f35aa-3f6b-41c1-91d9-8e279700ebf1/jobs/90

You should be able to lock the log4j dependency using:
```
./gradlew dependencies --update-locks 'org.apache.logging.log4j:*'
```
However if I'm not mistaken (I don't have too much experience with Gradle) this command reveals that other dependencies of `virtual-users` are depending on log4j 2.10.0, that is:
 * https://github.com/atlassian/concurrency
 * https://github.com/atlassian/jvm-tasks
I can see [your PR only for the latter](https://github.com/atlassian/jvm-tasks/pull/12), so I guess we still need a PR for `concurrency` module.

I hope this will help.

**Comment by rjatkins** [comment]
I think I've reached the bottom of this rabbit hole: the dependencies in both concurrency and jvm-tasks needed upgrades, and they're done now. However we can also sidestep the problem of needing releases of those by also using a resolutionStrategy to pin the version to 2.17.1 in here, so that's what I've done.

And I've seen from the conversation in help-jpt that there's a wider change to make to prevent implementation details like which logging backend is used (and what version of that) from leaking through. I'm going to leave that to your team to sort out, as this is going to need someone to touch every jpt component, not just these 3.

**Comment by gregrow** [comment]
log4j bumped in https://github.com/atlassian/virtual-users/pull/64

**Comment by gregrow** [comment]
log4j bumped in https://github.com/atlassian/virtual-users/pull/64

**Pull request closed without merging**
